[package]
name = "oh_db"
build = "build.rs"
version = "0.1.0"
authors = ["Terrence Cole <terrence.d.cole@gmail.com>"]

[dependencies]
argparse = "0.2"
env_logger = "0.3"
log = "0.3"
rand = "0.3"
rustc-serialize = "0.3"
capnp = "0.7"

[dependencies.ws]
version = "0.4"
features = ["ssl"]

[dependencies.openssl]
version = "*"
features = ["tlsv1_2", "ecdh_auto"]

[build-dependencies]
capnpc = "*"
